server:
  port: 8889

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/KindEgoist/microservice-config-repo
          clone-on-start: true
          default-label: main
